# Generated by Django 4.2.1 on 2023-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_companyvalue_visionidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-01 15:30:45.123456'),
            preserve_default=False,
        ),
    ]
