# Generated by Django 4.2.1 on 2023-11-02 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_companyvalue_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisionIdea',
            new_name='CompanyValueIdea',
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='value',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='PersonValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
